config/routes.rb
Rails.application.routes.draw do
  resources :comments, :topics, :resources, :users

  root 'topics#index'

  # login/logout methods
  get '/login', to: 'users#login'
  post '/login', to: 'users#login_post'
  get '/logout', to: 'users#logout'

  post '/comments', to: 'comments#show'

  get '/it-is-gonna-be-fine', to: 'comments#selfcare'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :resource_topics
  has_many :resources, :through => :resource_topics


  validates :name, :docs_url, :description, presence: true



end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    cookies[:link_id] = nil
    cookies[:link_path] = "/topics"
    
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])
    @resources = @topic.resources

    cookies[:link_id] = @topic.id
    cookies[:link_path] = "/topics/#{cookies[:link_id]}"

  end

  # GET /topics/new
  def new
    @topic = Topic.new

    cookies[:link_id] = nil
    cookies[:link_path] = "/topics/new"

  end

  # GET /topics/1/edit
  def edit
    binding.pry
    @topics = Topic.all

    cookies[:link_id] = @topic.id
    cookies[:link_path] = "/topics/#{cookies[:link_id]}/edit"


  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :docs_url, :description)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :docs_url %><br>
    <%= f.text_field :docs_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<% if session[:user_id] == nil %>
<div id="welcome-message">
<%= markdown("
#WELCOME TO PANIC BUTTON

**THIS IS STRESSFUL:** WDI is serious business, and the stuff we're doing is getting **COMPLICATED**. We all knew that going in, but it's still, y'know, pretty brutal.

**SO:** This is Panic Button. We know what we need to do, and collectively we can write the HELL out of this stuff. This site aims to capture that knowledge, store it online and make it retrievable.

**ALSO:** If you're stressing a LOT, click the button. That's why it's there.
") %>
</div>
<% else %>
<%= markdown("#TOPICS") %>
<% end %>

<button id="new-topic-button" class="submit-button">
  <%= link_to 'Submit A New Topic', new_topic_path %>
</button>

<div id="topics-container">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Docs</th>
      <th>Description</th>
      <% if current_user %>
        <th colspan="2">User Actions</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to topic.name, topic %></td>
        <td><%= link_to "Docs", topic.docs_url %></td>
        <td><%= topic.  description %></td>
        <% if current_user %>
          <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
          <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<div class='topic-details'>
<%=markdown("

##**Topic Overview**

**Name:** #{@topic.name}

**Docs:** #{link_to @topic.docs_url, @topic.docs_url}

**Description:** #{@topic.description}")%>
</div>

<div class='topic-links'>
<%=markdown("###**Available Resources**")%>
<% @resources.each do |t| %>
  <%=  markdown("* #{link_to t.name, t}") %>
<% end %>
</div>

<div class='bottom-nav'>
  <%= markdown("#{link_to 'Edit', edit_topic_path(@topic)} | #{link_to 'Back', topics_path } | #{ link_to 'Home', root_path }") %>
</div>