config/routes.rb
Rails.application.routes.draw do
  resources :comments, :topics, :resources, :users

  root 'topics#index'

  # login/logout methods
  get '/login', to: 'users#login'
  post '/login', to: 'users#login_post'
  get '/logout', to: 'users#logout'

  post '/comments', to: 'comments#show'

  get '/it-is-gonna-be-fine', to: 'comments#selfcare'

end

app/views/resources/edit.html.erb
<%= markdown("#Editing Resource")%>

<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <h3>Topics</h3>
    <% @topics.each do |t| %>
      <label name='topic'><%= t.name %></label>
      <input type="checkbox" name="topic_id[<%=t.id%>]" value="<%=t.id%>">
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= markdown("#{link_to 'Show', @resource} | #{ link_to 'Back', resources_path }")%>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resources</h1>

<table>
  <thead>
    <tr>
      <th>Week</th>
      <th>Name</th>
      <th>Description</th>
      <th>Link</th>
      <th>Last Edited By</th>
      <th colspan="3">User Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.week %></td>
        <td><%= link_to resource.name, resource %></td>
        <td><%= resource.description %></td>
        <td><%= link_to "Go", "#{resource.link}" %></td>
        <td><%= resource.user.name %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<%=markdown("#New Resource")%>

<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>

  <%= markdown("##**Topics:**") %>

  <% @topics.each do |t| %>
    <label name='topic'><%= t.name %></label>
    <input type="checkbox" name="topic_id[<%=t.id%>]" value="<%=t.id%>">
  <% end %>

  <br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<div class='resource-info'>
<%= markdown("
  **Name:**
  #{@resource.name}

  **Last Updated:**
  #{ @resource.updated_at }

  **Description:**
  #{ @resource.description }

  **Link:**
  #{ link_to @resource.link, @resource.link }

  **Logo:**
  #{image_tag @resource.img_url, height:42 }

  **Week:**
  #{ @resource.week }

  **User:**
  #{ @resource.user.name }
  ")%>


  <%= markdown("##**Topics:**") %>
  <% @topics.each do |t| %>
      <li><%=link_to t.name, topic_path(t.id)%></li>
  <% end %>

</div>

<br>

<% if current_user %>
  <%= link_to 'Edit Item', edit_resource_path(@resource) %>
  <%= link_to 'Destroy', @resource, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<div id="resource-comments" >

    <%=markdown("**<label for='comments'> Comments: </label>**")%>
    <% @comments.each do |comment| %>
      <%= markdown( "* #{comment.content} - #{comment.user.first_name }") %>
    <% end %>

    <% if current_user %>
      <button><%= link_to "Add New Comment", new_comment_path %></button>
    <% else %>
      <button id="please-login" href="/login">Login</button>
    <% end %>

</div>

<br>


<%= link_to 'Back', resources_path %> |
<%= link_to 'Home', root_path %>